# Generated by Django 3.2.6 on 2021-08-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='date',
        ),
    ]
