# Generated by Django 3.2.6 on 2021-08-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('matter', models.CharField(max_length=254)),
                ('query', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Contact',
            },
        ),
    ]
